# Generated by Django 5.2 on 2026-02-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_options_alter_discount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение (файл)'),
        ),
    ]
