# Generated by Django 5.2 on 2026-02-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_uploaded_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150, verbose_name='Автор')),
                ('company', models.CharField(blank=True, default='', max_length=200, verbose_name='Компания')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Оценка')),
                ('image', models.URLField(blank=True, default='', max_length=300, verbose_name='Логотип/изображение (URL)')),
                ('source_url', models.URLField(blank=True, default='', max_length=300, verbose_name='Источник')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('sort_order', '-created_at'),
            },
        ),
    ]
