# Generated by Django 5.2 on 2026-02-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название кампании')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('caption', models.CharField(blank=True, default='', max_length=255, verbose_name='Подзаголовок')),
                ('button_text', models.CharField(blank=True, default='Перейти в каталог', max_length=80, verbose_name='Текст кнопки')),
                ('button_url', models.CharField(blank=True, default='/store', max_length=255, verbose_name='Ссылка кнопки')),
                ('desktop_image', models.URLField(max_length=500, verbose_name='Изображение desktop (URL)')),
                ('mobile_image', models.URLField(blank=True, default='', max_length=500, verbose_name='Изображение mobile (URL)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('starts_on', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Hero-баннер',
                'verbose_name_plural': 'Hero-баннеры',
                'ordering': ('sort_order', '-created_at'),
            },
        ),
    ]
