# Generated by Django 5.2 on 2026-02-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_herobanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_online_showcase',
            field=models.BooleanField(default=False, verbose_name='Показывать в ONLINE витрине'),
        ),
        migrations.AddField(
            model_name='product',
            name='showcase_channel',
            field=models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз'), ('both', 'И доставка, и самовывоз')], default='both', max_length=16, verbose_name='Канал витрины'),
        ),
        migrations.AddField(
            model_name='product',
            name='showcase_sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок в витрине'),
        ),
    ]
