# Generated by Django 5.2 on 2026-02-14 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_is_online_showcase_product_showcase_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(blank=True, default='', help_text='Пустой поддомен = основной домен', max_length=50, unique=True, verbose_name='Поддомен')),
                ('name', models.CharField(max_length=100, verbose_name='Название магазина')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('address', models.TextField(blank=True, default='', verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, default='', verbose_name='Изображение (URL)'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.store', verbose_name='Магазин'),
        ),
        migrations.CreateModel(
            name='StoreManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, default='', max_length=100, verbose_name='Username')),
                ('full_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('stores', models.ManyToManyField(related_name='managers', to='shop.store', verbose_name='Магазины')),
            ],
            options={
                'verbose_name': 'Менеджер магазина',
                'verbose_name_plural': 'Менеджеры магазинов',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to='shop.storemanager', verbose_name='Добавил менеджер'),
        ),
    ]
