# Generated by Django 5.2 on 2026-02-14 04:15

from django.db import migrations


def seed_default_stores(apps, schema_editor):
    Store = apps.get_model('shop', 'Store')
    stores = [
        {'subdomain': '', 'name': 'Основной магазин (buket.by)'},
        {'subdomain': 'dana-mall', 'name': 'Dana Mall'},
        {'subdomain': 'gallery-minsk', 'name': 'Gallery Minsk'},
        {'subdomain': 'minsk-city-mall', 'name': 'Minsk City Mall'},
    ]
    for data in stores:
        Store.objects.get_or_create(subdomain=data['subdomain'], defaults={'name': data['name']})


def unseed_default_stores(apps, schema_editor):
    Store = apps.get_model('shop', 'Store')
    Store.objects.filter(subdomain__in=['', 'dana-mall', 'gallery-minsk', 'minsk-city-mall']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_store_product_is_published_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_default_stores, reverse_code=unseed_default_stores),
    ]
