# Generated by Django 5.2 on 2026-02-18 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_categories_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stores',
            field=models.ManyToManyField(blank=True, related_name='products_m2m', to='shop.store', verbose_name='Магазины'),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.store', verbose_name='Магазин (legacy)'),
        ),
    ]
