# Generated by Django 5.2 on 2026-02-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_migrate_product_store_to_m2m_and_deduplicate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
    ]
