# Generated by Django 5.2 on 2026-02-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_product_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название цветка')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тег (цветок)',
                'verbose_name_plural': 'Теги (цветы)',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='flower_tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.flowertag', verbose_name='Состав (цветы)'),
        ),
    ]
