# Generated by Django 5.2 on 2026-02-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_herobanner_image_fields_and_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=120, verbose_name='Slug (ЧПУ)'),
        ),
        migrations.AddField(
            model_name='flowertag',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=120, verbose_name='Slug (ЧПУ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Заполняется автоматически из названия или старой БД', max_length=120, verbose_name='Slug (ЧПУ)'),
        ),
    ]
