# Generated by Django 5.2 on 2026-02-21 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_add_sitepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ('sort_order', 'name'), 'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание / как добраться'),
        ),
        migrations.AddField(
            model_name='store',
            name='map_embed_url',
            field=models.TextField(blank=True, default='', help_text='Вставьте src="" из iframe Яндекс/Google карт', verbose_name='Код карты (iframe src)'),
        ),
        migrations.AddField(
            model_name='store',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='store',
            name='working_hours',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон (устар.)'),
        ),
        migrations.CreateModel(
            name='StorePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(blank=True, choices=[('📞', '📞 Телефон'), ('📱', '📱 Мобильный'), ('💬', '💬 WhatsApp/Viber'), ('✉️', '✉️ Email'), ('🕐', '🕐 Доп. время'), ('', 'Без эмоджи')], default='📞', max_length=10, verbose_name='Эмоджи')),
                ('label', models.CharField(blank=True, default='', max_length=50, verbose_name='Подпись (напр. «Заказы»)')),
                ('number', models.CharField(max_length=50, verbose_name='Номер / контакт')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='shop.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Телефон магазина',
                'verbose_name_plural': 'Телефоны магазина',
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='StorePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stores/', verbose_name='Фото интерьера')),
                ('caption', models.CharField(blank=True, default='', max_length=200, verbose_name='Подпись')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='shop.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Фото магазина',
                'verbose_name_plural': 'Фото магазина',
                'ordering': ('sort_order',),
            },
        ),
    ]
