# Generated by Django 5.2 on 2026-02-21 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_storemanager_user_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='shop.store', verbose_name='Магазин'),
        ),
    ]
