# Generated by Django 5.2 on 2026-02-22 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_review_store_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_items', to='shop.product', verbose_name='Товар')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_items', to='shop.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Товар в витрине',
                'verbose_name_plural': 'Товары в витринах',
                'ordering': ('sort_order', '-id'),
                'unique_together': {('store', 'product')},
            },
        ),
    ]
