# Generated by Django 5.2 on 2026-02-22 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=15, max_digits=8, verbose_name='Стоимость доставки (BYN)')),
                ('delivery_free_from', models.DecimalField(decimal_places=2, default=100, max_digits=8, verbose_name='Бесплатная доставка от (BYN)')),
                ('notification_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email для уведомлений о заказах')),
                ('telegram_notify_token', models.CharField(blank=True, default='', help_text='Токен бота, который будет слать уведомления', max_length=200, verbose_name='Telegram Bot Token для уведомлений')),
                ('telegram_notify_chat_id', models.CharField(blank=True, default='', help_text='ID чата или группы, куда слать уведомления о заказах', max_length=100, verbose_name='Telegram Chat ID для уведомлений')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='GuestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('customer_phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('recipient_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Имя получателя')),
                ('recipient_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон получателя')),
                ('delivery_type', models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')], default='delivery', max_length=16, verbose_name='Способ доставки')),
                ('delivery_address', models.TextField(blank=True, default='', verbose_name='Адрес доставки')),
                ('delivery_date', models.CharField(blank=True, default='', max_length=50, verbose_name='Дата доставки')),
                ('delivery_time', models.CharField(blank=True, default='', max_length=50, verbose_name='Время доставки')),
                ('payment_type', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Оплата картой online')], default='cash', max_length=16, verbose_name='Способ оплаты')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма товаров')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Стоимость доставки')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итого к оплате')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий к заказу')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтверждён'), ('done', 'Выполнен'), ('cancelled', 'Отменён')], default='new', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('pickup_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_orders_pickup', to='shop.store', verbose_name='Магазин самовывоза')),
            ],
            options={
                'verbose_name': 'Гостевой заказ',
                'verbose_name_plural': 'Гостевые заказы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GuestOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название (на момент заказа)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (на момент заказа)')),
                ('qty', models.PositiveIntegerField(verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.guestorder', verbose_name='Заказ')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
    ]
