# Generated by Django 5.2 on 2026-02-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_add_site_settings_guest_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepage',
            name='seo_description',
            field=models.CharField(blank=True, default='', help_text='До 160 символов. Если пусто — генерируется автоматически.', max_length=320, verbose_name='SEO описание (meta description)'),
        ),
    ]
