# Generated by Django 5.2 on 2026-03-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_set_komsomolskaya_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='metrika_counter',
            field=models.TextField(blank=True, default='', help_text='Вставьте полный JS-код счётчика из Яндекс.Метрики (тег <script>...)', verbose_name='Код счётчика Яндекс.Метрики'),
        ),
    ]
