# Generated by Django 5.2 on 2026-03-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_add_metrika_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(max_length=255, unique=True, verbose_name='Ключ сессии')),
                ('bot_id', models.BigIntegerField(verbose_name='Bot ID')),
                ('chat_id', models.BigIntegerField(verbose_name='Chat ID')),
                ('user_id', models.BigIntegerField(verbose_name='User ID')),
                ('thread_id', models.BigIntegerField(blank=True, null=True, verbose_name='Thread ID')),
                ('business_connection_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Business connection ID')),
                ('destiny', models.CharField(default='default', max_length=64, verbose_name='Destiny')),
                ('state', models.CharField(blank=True, default='', max_length=255, verbose_name='FSM state')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='FSM data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Сессия Telegram-бота',
                'verbose_name_plural': 'Сессии Telegram-бота',
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['chat_id', 'user_id'], name='shop_telegr_chat_id_19573e_idx')],
            },
        ),
    ]
